name: hashicorp/hashicat-aws/infrastructure-tests
on:
  workflow_dispatch: 
  push:
    branches:
      - 'master'
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Terraform Validate
        run: |-
          terraform init
          terraform validate
permissions:
  contents: read